import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { ExamplesNav } from "@/components/examples-nav";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container relative">
            <div className="mt-4"></div>
            <section>
              <ExamplesNav />
              <div className="overflow-hidden rounded-[0.5rem] border bg-background shadow">
                {children}
              </div>
            </section>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
