export interface Sponsor {
  id: string;
  englishName: string;
  chineseName: string;
  country: string;
  type: string;
  website: string;
}

export const sponsors: Sponsor[] = [
  {
    id: "1",
    englishName: "ABB Engineering (Shanghai) Ltd",
    chineseName: "上海ABB工程有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://new.abb.com/",
  },
  {
    id: "2",
    englishName: "Shanghai Xiteng Electronic Information Technology Co Ltd",
    chineseName: "上海希腾电子信息技术有限责任公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.shanghai-electric.com/",
  },
  {
    id: "3",
    englishName: "Transfar Zhilian Co Ltd",
    chineseName: "传化智联股份有限公司",
    country: "China",
    type: "民营公司",
    website: "https://www.etransfar.com/",
  },
  {
    id: "4",
    englishName: "Yiyun Zhiai Technology (Shenzhen) Co Ltd",
    chineseName: "一云智爱科技(深圳)有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://gookytech.en.alibaba.com/",
  },
  {
    id: "5",
    englishName: "Beijing Jijia Technology Co Ltd",
    chineseName: "北京积加科技有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "http://www.zhjjtech.com/en/",
  },
  {
    id: "6",
    englishName: "Shanghai Yinhang Information Technology Co LTD",
    chineseName: "上海音航信息科技有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "",
  },
  {
    id: "7",
    englishName: "Shanghai Xiaoxiliushui Business Consulting Co LTD",
    chineseName: "上海小溪流水商务咨询有限责任公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "",
  },
  {
    id: "8",
    englishName: "Shanghai Xiaoxiliushui Business Consulting Co LTD",
    chineseName: "上海小溪流水商务咨询有限责任公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "",
  },
  {
    id: "9",
    englishName: "Shanghai NIO Co Ltd",
    chineseName: "上海蔚来汽车有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.nio.com/",
  },
  {
    id: "10",
    englishName: "United Automotive Electronic Systems Co Ltd",
    chineseName: "联合汽车电子有限公司",
    country: "China",
    type: "中外合资企业",
    website: "https://www.uaes.com/",
  },
  {
    id: "11",
    englishName: "Shanghai TechBank Medical Co Ltd",
    chineseName: "上海科库医疗技术有限公司",
    country: "China",
    type: "有限责任公司（非自然人投资或控股的法人独资）",
    website: "http://www.techbankmed.com/en/",
  },
  {
    id: "12",
    englishName: "GM (China) Investment Co Ltd",
    chineseName: "通用汽车（中国）投资有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.gmchina.com/",
  },
  {
    id: "13",
    englishName: "Rockwell Automation (China) LTD",
    chineseName: "罗克韦尔自动化（中国）有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.rockwellautomation.com/",
  },
  {
    id: "14",
    englishName: "HASCO VISION Technology (Shanghai) Co Ltd",
    chineseName: "华域视觉科技（上海）有限公司",
    country: "China",
    type: "有限责任公司（非自然人投资或控股的法人独资）",
    website: "https://hvus.hascovision.com/",
  },
  {
    id: "15",
    englishName: "Intel Asia Pacific Research and Development Ltd",
    chineseName: "英特尔亚太研发有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.intel.com/",
  },
  {
    id: "16",
    englishName: "Hangzhou AIMS Intelligent Technology Co Ltd",
    chineseName: "杭州安脉盛智能技术有限公司",
    country: "China",
    type: "民营公司",
    website: "https://www.aimsphm.com/",
  },
  {
    id: "17",
    englishName: "Beijing Builderx Intelligent Technology Co Ltd",
    chineseName: "北京拓疆者智能科技有限公司",
    country: "China",
    type: "民营公司",
    website: "",
  },
  {
    id: "18",
    englishName: "Shenzhen Sunway Communication CO LTD",
    chineseName: "深圳市信维通信股份有限公司",
    country: "China",
    type: "民营公司",
    website: "https://en.sz-sunway.com/",
  },
  {
    id: "19",
    englishName: "Bosch (Shanghai) Smart Life Technology Ltd (RBLC)",
    chineseName: "博世（上海）智能科技有限公司",
    country: "China",
    type: "有限责任公司（外国法人独资）",
    website: "https://www.bosch.com/",
  },
  {
    id: "20",
    englishName: "Suzhou Sophoton Tech Co Ltd",
    chineseName: "苏州识光芯科技术有限公司",
    country: "China",
    type: "民营公司",
    website: "https://uspto.report/TM/97052494",
  },
  {
    id: "21",
    englishName: "Shanghai Nexmaterials Technology Co Ltd",
    chineseName: "Shanghai Nexmaterials Technology Co Ltd",
    country: "China",
    type: "民营公司",
    website: "",
  },
  {
    id: "22",
    englishName: "ChinaScope (Shanghai) Techno Co Ltd",
    chineseName: "ChinaScope (Shanghai) Techno Co Ltd",
    country: "China",
    type: "民营公司",
    website: "http://chinascope.org/",
  },
  {
    id: "23",
    englishName: "Beijing TerraQuanta Technology Co Ltd",
    chineseName: "Beijing TerraQuanta Technology Co Ltd",
    country: "China",
    type: "民营公司",
    website: "http://terraqt.com/",
  },
  {
    id: "24",
    englishName: "Shanghai United Imaging Healthcare Co Ltd",
    chineseName: "Shanghai United Imaging Healthcare Co Ltd",
    country: "China",
    type: "民营公司",
    website: "https://www.united-imaging.com/en/",
  },
  {
    id: "25",
    englishName:
      "Mega Phase Industrial Inspection Technology (Shanghai) Co Ltd",
    chineseName:
      "Mega Phase Industrial Inspection Technology (Shanghai) Co Ltd",
    country: "China",
    type: "民营公司",
    website: "http://www.megaphase3d.com/en",
  },
  {
    id: "26",
    englishName: "VMware Information Technology (China) Co Ltd",
    chineseName: "VMware Information Technology (China) Co Ltd",
    country: "China",
    type: "民营公司",
    website: "https://www.vmware.com/",
  },
];
